var LEA = {};
LEA.sPath = "https:\/\/dn-leanote.qbox.me";
LEA.locale = "en";
var UrlPrefix = 'http:\/\/leanote.com';
var UserInfo = {"UserId":"56a82c7bab64417776002a5c","Email":"me@nottingham.edu.cn","Verified":false,"Username":"me@nottingham.edu.cn","UsernameRaw":"","CreatedTime":"0001-01-01T00:00:00Z","Logo":"http://leanote.com/images/blog/default_avatar.png","Theme":"","NotebookWidth":0,"NoteListWidth":0,"MdEditorWidth":0,"LeftIsMin":false,"ThirdUserId":"","ThirdUsername":"","ThirdType":0,"FromUserId":"","NoteCnt":0,"Usn":10,"FullSyncBefore":"0001-01-01T00:00:00Z","BlogUrl":"","PostUrl":""};
var notebooks;
var shareNotebooks;
var sharedUserInfos;
var curNoteId;
var curNotebookId;
var curSharedNoteNotebookId;
var curSharedUserId;
var notes;
var latestNotes;
var noteContentJson;
var tagsJson = [];
var GlobalConfigs = {"uploadAttachSize":0,"uploadAvatarSize":0,"uploadBlogLogoSize":0,"uploadImageSize":0};
var tinyMCEPreInit = {base: 'https:\/\/dn-leanote.qbox.me/tinymce_4.1.9/js/tinymce', suffix: '.min'};

var trackingLog;