language: node_js
node_js:
  - "0.10"
env:
  - t=unit
  - t=unit BROWSERS=PhantomJS
  - t=unit BROWSERS=Firefox
  - t=integration
  - t=integration BROWSERS=PhantomJS,Firefox
matrix:
  # just run unit tests on other node versions
  include:
    - node_js: "0.11"
      env: t=unit
    - node_js: "0.8"
      env: t=unit
  
  allow_failures:
    - node_js: "0.10"
      env: t=integration
    - node_js: "0.10"
      env: t=integration BROWSERS=PhantomJS,Firefox
    - node_js: "0.10"
      env: t=unit BROWSERS=Firefox
    - node_js: "0.11"
      env: t=unit
notifications:
  email:
    recipients:
      - commits@onilabs.com
    on_success: change
    on_failure: always
branches:
  # build only master and release braches
  only:
    - master
    - /^\d+(\.\d+)+$/

# nodejs 0.6 is pretty much dead, but this'll keep it limping for a little while...
before_install:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.8" ]; then npm -g install npm@~1.4.6; fi'

script: "./tools/bin/sjs-tests --show-failed"

